#!/bin/bash

########
#
# simple gplv2 script to change an xml sitemap to an html file full of links
# 
# if you can use it, then great :D by Jonathan Mitchell
# jonathansblog.co.uk 
#
########

# input file check function
function checkinput {
	# does the file exist?
	if [ -f $1 ];then
		# dont exit
		echo ""
	else
		echo "$1 doesnt exist"
		exit 
		#"input file $1 doesnt exist"
	fi	
}

# output file check function
function checkoutput {
	# does the file exist?
	if [ -f $1 ];then 
		# dont exit, nuke the file
		echo > $1
	else
		# create it
		echo > $1
	fi
}

# help function
function help {
	echo ""
	echo "sitemap-xml-to-html script"
	echo "by jonathan at jonathansblog.co.uk"
	echo ""
	echo "usage: "
	echo "sitemap-xml-to-html input_file output_file"
	echo ""
}


if [ "$1" = "-h" ] || [ -z $1 ] || [ -z $2 ]; then
	help
else
	checkinput $1
	checkoutput $2
	urls=`cat $1 | grep loc | sed 's#<loc>##g' | sed 's#</loc>##g'`
	# now we only have urls, need to turn them into anchor tags...
	for url in $urls ; do
		echo '<a href="'$url'">'$url'</a>' >> $2
	done
	echo "$2 has been created"
fi
