#!/bin/bash

########
#
# simple gplv2 script to change an xml sitemap to an html file full of links
#
# if you can use it, then great :D by Jonathan Mitchell
# jonathansblog.co.uk
#
########

# input file check function
function checkinput {
	# does the file exist?
	if [ -f $1 ];then
		# dont exit
		echo ""
	else
		echo "$1 doesnt exist"
		exit
		#"input file $1 doesnt exist"
	fi
}

# help function
function help {
	echo ""
	echo "sitemap-xml-to-html script with w3c nu validation"
	echo "by jonathan at jonathansblog.co.uk"
	echo ""
	echo "usage: "
	echo "sitemap-xml-to-html -validator input_file"
	echo ""
	echo "output will be to result.html so you can view it in a broswer"
}


if [ "$1" = "-h" ] || [ -z $1 ]; then
	help
else
	checkinput $1
	echo '<!DOCTYPE html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous"></head><body><div class="container">';
	urls=`cat $1 | grep "<loc>" | sed 's#<loc>##g' | sed 's#</loc>##g'`
	# now we only have urls, need to turn them into anchor tags...
	for url in $urls ; do
    	encoded=$(php -r "echo rawurlencode('$url');")
		echo '<a target="_new" href="https://validator.w3.org/nu/?doc='$encoded'">'$url'</a><br/>'
        var=$(./w3c-check $url 2> ~/tempfile)
        echo '<blockquote>'
    	content=$(cat ~/tempfile)
        html_content=$(php -r "echo nl2br('$content');")
        echo $html_content
        echo '</blockquote>'
	rm ~/tempfile
	echo '<hr>'
	done

    echo '</div></body>'
fi
